# Generated by Django 4.2.6 on 2024-02-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_is_admin_usuario_is_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
