# Generated by Django 4.2.6 on 2024-02-21 16:22

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('nivel', '0002_puntucionnivelusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntucionnivelusuario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=datetime(2024, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
