# Generated by Django 4.2.6 on 2023-10-31 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
        ('partida', '0002_partida_juego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.juego'),
        ),
    ]
